version: '3'
services:
  nodejs:
    build: ./.docker/nodejs
    networks:
      - "ensiie"
    ports:
       - "3000:3000"
    volumes: 
      - "./:/usr/src/app/"

  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - ${DB_PORT_EXTERNAL}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - "ensiie"

networks:
    ensiie:
        driver: bridge
