version: '3.7'
services:
  nodejs:
    build: ./.docker/nodejs
    expose:
      - "3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: "3000"
    ports:
       - "3000:3000"
    volumes: 
      - "./:/usr/src/app/"
    
  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - ${DB_PORT_EXTERNAL}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html

  mountebank:
    container_name: mountebank
    image: jkris/mountebank:latest
    volumes:
    - ./imposters:/imposters
    ports:
    - 2525:2525
    - 8090:8090
    command: --configfile /imposters/imposters.ejs --allowInjection

  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:4.0.1"
    depends_on:
      - nodejs
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://0.0.0.0:3000/
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
